sudo: required
service: docker

before_install:
  - docker pull nimlang/nim:1.2.4
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/WD" -w /WD --rm nimlang/nim:1.2.4 sh -c "apt install -y zip zlib1g-dev && nimble install -y --verbose"
