title: BamToCov
repository: telatin/bamtocov
lang: en
description: "BamToCov - alignment coverage tools"

readme_index:
  with_frontmatter: true

theme: null

remote_theme: rundocs/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-gist

markdown: CommonMarkGhPages
commonmark:
  options: ['SMART']
  extensions: ['table']
